apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydevops
  template:
    metadata:
      labels:
        app: mydevops
    spec:
      containers:
      - name: mydevops
        image: xeeshanakram/zenix:v1.9
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
